name: Build Fabric Mod

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build and Upload JAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Upload built mod jar
      uses: actions/upload-artifact@v4
      with:
        name: tock-alpha-build
        path: build/libs/*.jar
